export const PERMISSIONS = {
  SUPPORT: 'SUPPORT',

  ERP_SALES: {
    VIEW: 'ERP_SALES_CONSULT',
    CREATE: 'ERP_SALES_CREATE',
    DELETE: 'ERP_SALES_DELETE',
    CHANGE: 'ERP_SALES_CHANGE',
    ACTIVE_OR_INACTIVE: 'ERP_SALES_ACTIVE_OR_INACTIVE',
  },

  ERP_PARCELS: {
    VIEW: 'ERP_PARCELS_CONSULT',
    CREATE: 'ERP_PARCELS_CREATE',
    DELETE: 'ERP_PARCELS_DELETE',
    CHANGE: 'ERP_PARCELS_CHANGE',
    ACTIVE_OR_INACTIVE: 'ERP_PARCELS_ACTIVE_OR_INACTIVE',
  },

  USERS: {
    VIEW: 'USERS_CONSULT',
    CREATE: 'USERS_CREATE',
    DELETE: 'USERS_DELETE',
    CHANGE: 'USERS_CHANGE',
    ACTIVE_OR_INACTIVE: 'USERS_ACTIVE_OR_INACTIVE',
  },

  COMPANIES: {
    VIEW: 'COMPANIES_CONSULT',
    CREATE: 'COMPANIES_CREATE',
    DELETE: 'COMPANIES_DELETE',
    CHANGE: 'COMPANIES_CHANGE',
    ACTIVE_OR_INACTIVE: 'COMPANIES_ACTIVE_OR_INACTIVE',
  },

  ACQUIRER: {
    VIEW: 'ACQUIRER_CONSULT',
    CREATE: 'ACQUIRER_CREATE',
    DELETE: 'ACQUIRER_DELETE',
    CHANGE: 'ACQUIRER_CHANGE',
    MANAGE_RELATIONS: 'ACQUIRER_MANAGE_RELATIONS',
    ACTIVE_OR_INACTIVE: 'ACQUIRER_ACTIVE_OR_INACTIVE',
  },

  ESTABLISHMENT: {
    VIEW: 'ESTABLISHMENT_CONSULT',
    CREATE: 'ESTABLISHMENT_CREATE',
    DELETE: 'ESTABLISHMENT_DELETE',
    CHANGE: 'ESTABLISHMENT_CHANGE',
    ACTIVE_OR_INACTIVE: 'ESTABLISHMENT_ACTIVE_OR_INACTIVE',
  },

  FLAGS: {
    VIEW: 'FLAGS_CONSULT',
    CREATE: 'FLAGS_CREATE',
    DELETE: 'FLAGS_DELETE',
    CHANGE: 'FLAGS_CHANGE',
    MANAGE_RELATIONS: 'FLAGS_MANAGE_RELATIONS',
    ACTIVE_OR_INACTIVE: 'FLAGS_ACTIVE_OR_INACTIVE',
  },

  CONTRACTS: {
    VIEW: 'CONTRACTS_CONSULT',
    CREATE: 'CONTRACTS_CREATE',
    DELETE: 'CONTRACTS_DELETE',
    CHANGE: 'CONTRACTS_CHANGE',
    ACTIVE_OR_INACTIVE: 'CONTRACTS_ACTIVE_OR_INACTIVE',
  },

  GROUPS: {
    VIEW: 'GROUPS_CONSULT',
    CREATE: 'GROUPS_CREATE',
    DELETE: 'GROUPS_DELETE',
    CHANGE: 'GROUPS_CHANGE',
    MANAGE_USERS: 'GROUP_MANAGEMENT_USER',
    ACTIVE_OR_INACTIVE: 'GROUPS_ACTIVE_OR_INACTIVE',
    MANAGE_PERMISSIONS: 'GROUP_MANAGEMENT_PERMISSION',
  },

  AUDIT: {
    VIEW: 'AUDIT_MAIL_CONSULT',
  },
} as const;

type ValueOf<T> = T[keyof T];
type DeepValueOf<T> = T extends object ? DeepValueOf<ValueOf<T>> : T;

export type Permission = DeepValueOf<typeof PERMISSIONS>;

export const ALL_PERMISSIONS: Permission[] = [
  PERMISSIONS.SUPPORT,
  ...Object.values(PERMISSIONS.USERS),
  ...Object.values(PERMISSIONS.COMPANIES),
  ...Object.values(PERMISSIONS.ACQUIRER),
  ...Object.values(PERMISSIONS.ESTABLISHMENT),
  ...Object.values(PERMISSIONS.FLAGS),
  ...Object.values(PERMISSIONS.CONTRACTS),
  ...Object.values(PERMISSIONS.GROUPS),
  ...Object.values(PERMISSIONS.AUDIT),
];
